import { MemberQrRepository } from './memberQr.repository.js';
import { MemberRepository } from '../member/member.repository.js';
import createError from 'http-errors';
import QRCode from 'qrcode';
import crypto from 'crypto';
import { env } from '../config/env.js';

export class MemberQrService {
  /**
   * Generates a cryptographically signed payload for the QR code
   * so scanners can verify it was generated by our system and not spoofed.
   */
  static generateSecurePayload(gymId, memberId) {
    const payload = `${gymId}:${memberId}:${Date.now()}`;
    const hash = crypto.createHmac('sha256', env.JWT_SECRET).update(payload).digest('hex');
    return `${payload}:${hash}`;
  }

  static async generateQr(gymId, memberId) {
    const member = await MemberRepository.findById(memberId, gymId);
    if (!member) throw createError.NotFound('Member not found');

    const qrCodeData = this.generateSecurePayload(gymId, memberId);
    
    // Generate base64 SVG or PNG image data
    const base64Image = await QRCode.toDataURL(qrCodeData, {
      errorCorrectionLevel: 'H',
      margin: 1,
      width: 400,
      color: {
        dark: '#000000',
        light: '#ffffff'
      }
    });

    return MemberQrRepository.upsert(gymId, memberId, qrCodeData, base64Image);
  }

  static async getQr(gymId, memberId) {
    const qr = await MemberQrRepository.findByMemberId(gymId, memberId);
    if (!qr) throw createError.NotFound('QR Code not found for this member');
    return qr;
  }
}
